feat: jet 部署 helm chart
Byzanteam/jet-helm-chart pull request #1
Opened 2023-10-09 09:14 UTC by YkeLit

1. 创建 jet deployment 资源清单
2. 创建 jet service 资源清单
3. 创建 jet 环境变量 configMap
4. 创建 jet 镜像拉取凭证与 tls 证书凭证
5. 创建 jet 入口 ingressroute 资源清单
6. 创建 jet 入口所需 middleware ( compress, strip prefix, cors, redirect https)

2023-10-09 11:24 UTC, fahchen reviewed
这个 helm-chart 我们有几个服务
1. project_man
2. trace_aware
3. breeze
4. 后面可能还有其他

所以这个 chart 里面的这些变量参数注意区分一下

2023-10-09 11:24 UTC, fahchen commented on values.yaml
> +  CREDENTIAL_SECRET: gBgN6F4183LXKFbiE59K/zq+VuX1m3x2cf1lry+TEdflE3i4IjUYGObOlmyKm2Op
不给密钥
```suggestion
  CREDENTIAL_SECRET: my-credential-secret
```

2023-10-09 11:24 UTC, fahchen commented on values.yaml
> +  SECRET_KEY_BASE: Sl7ym/kDmxL7mcZzkY7S/zLEP9Ybkp4aqTnE/BoHQfsGAwnKqQaKfyzWPs4pAebU
```suggestion
  SECRET_KEY_BASE: my-secret-key-base
```

2023-10-09 11:24 UTC, fahchen commented on values.yaml
> +    repository: jet
```suggestion
    repository: breeze
```

2023-10-09 11:24 UTC, fahchen commented on values.yaml
> +  # - /plugin/graphql.sdl
这个为什么做成可以配置的呢？

2023-10-09 11:24 UTC, fahchen commented on values.yaml
> +  # accessControlMaxAge: "100"
middleware 放一起吧

2023-10-09 11:24 UTC, fahchen commented on values.yaml
> +    # key: base64 encoding key-file
这个是不是用 k8s 的 secret 来管理

2023-10-09 11:24 UTC, fahchen commented on templates/secrets/docker-registry.yaml
这个是不是我们引用 k8s 的一个 secret，而不是我们自己创建一个？

2023-10-09 11:24 UTC, fahchen commented on templates/configmap/jet.yaml
> +  name: {{ .Chart.Name }}-env
name 应该不对，不是 chart name

2023-10-09 11:24 UTC, fahchen commented on templates/deployment.yaml
> +        - name: {{ .Chart.Name }}
这个为什么直接事 chart name 呢？
```suggestion
        - name: {{ include "jet-helm-chart.image" . }}-jet
```

2023-10-09 11:24 UTC, fahchen commented on values.yaml
> +env:
这里是不是把 breeze，jet，trace_aware 的 env 分开呀？

2023-10-09 11:24 UTC, fahchen commented on values.yaml
> +jetStripPrefix: ""
这里设计成一个变量 `subpath` 吧

1. https://github.com/rails/rails/blob/main/guides/source/configuring.md#configrelative_url_root
2. https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#module-runtime-configuration

2023-10-23 06:14 UTC, YkeLit commented
@fahchen 飞哥有空看一下

2023-10-24 00:17 UTC, fahchen requested changes

2023-10-24 00:17 UTC, fahchen commented on Chart.yaml
> +    alias: dynamicdb
这个名字我想还是调整一下叫做 projectsdb
@vanppo

2023-10-24 00:17 UTC, fahchen commented on README.md
> +| jetdb.auth.postgresPassword | string | `"changeit"` | postgres 用户密码设置 |
这个能做到 secret 里面不呀，其它的 password 也一样

2023-10-24 00:17 UTC, fahchen commented on README.md
> +| jetTLS | object | `{}` | tls 证书 |
这个也做的 secret 里面一下吧

2023-10-24 00:17 UTC, fahchen commented on templates/_helpers.tpl
> +{{- define "jet-helm-chart.imagePullSecret" }}
这个走 secret 呢

2023-10-24 00:17 UTC, fahchen commented on templates/_helpers.tpl
> +{{- define "jet-helm-chart.jetHosts" -}}
这个 helper 的命名不太贴切

2023-10-24 00:17 UTC, fahchen commented on templates/_helpers.tpl
> +{{- define "jet-helm-chart.selectorLabels" -}}
selector-labels 还是小驼峰呢，看看有没规范，统一一下

2023-10-24 00:17 UTC, fahchen commented on templates/breeze/_helpers.tpl
> +{{- if .Chart.AppVersion }}
这个条件判断有什么意图呀

2023-10-24 00:17 UTC, fahchen commented on templates/breeze/deployment.yaml
> +            - 'http://{{ include "jet-helm-chart.fullname" . }}-project-man:{{ .Values.projectMan.service.prot }}'
```suggestion
            - 'http://{{ include "jet-helm-chart.fullname" . }}-project-man:{{ .Values.projectMan.service.port }}'
```

2023-10-24 00:17 UTC, fahchen commented on templates/breeze/deployment.yaml
> +                name: {{ include "jet-helm-chart.fullname" . }}-env
这个分开写一下，breeze 用自己的 env（内容现在可以都一样，开发进来调整）

2023-10-24 00:17 UTC, fahchen commented on templates/breeze/ingressroute.yaml
> +{{- $webMiddlewares = append $webMiddlewares "redirect-to-https" }}
这个有没可能在 ingress route 层面做一次呢，而不是每个都做一下（比如 breeze，project_man 都做了一次）

2023-10-24 00:17 UTC, fahchen commented on templates/projectman/_helpers.tpl
> +{{- define "jet-helm-chart.projectMan-image" }}
```suggestion
{{- define "jet-helm-chart.project-man-image" }}
```

2023-10-24 00:17 UTC, fahchen commented on templates/projectman/_helpers.tpl
> +app.kubernetes.io/application: projectMan
```suggestion
app.kubernetes.io/application: project-man
```

2023-10-24 00:17 UTC, fahchen commented on templates/projectman/service.yaml
文件路径
projectman -> project-man

2023-10-24 00:17 UTC, fahchen commented on templates/traceaware/_helpers.tpl
> +Return the jet image name
注释和实际内容不符合

2023-10-24 00:17 UTC, fahchen commented on templates/traceaware/deployment.yaml
> +            - 'until psql -c "SELECT 1" "user=postgres password={{ .Values.jetdb.auth.postgresPassword }} dbname=trace_aware_prod host={{ .Values.jetdb.fullnameOverride }}"; do echo waiting for trace
trace-aware 和 project-man 用的是一个数据库实例吗？
@vanppo

2023-10-24 00:17 UTC, fahchen commented on values.yaml
> +jetHosts: []
不用带 jet 前缀

2023-10-24 00:17 UTC, fahchen commented on values.yaml
> +  jetSubpath: ""
这个提升到 host 那一层吧
```suggestion
  subpath: ""
```

2023-10-24 00:17 UTC, fahchen commented
别 force push 哈

2023-10-24 02:00 UTC, vanppo commented on Chart.yaml
> +    alias: dynamicdb
Jet 代码要调吗

2023-10-24 02:02 UTC, vanppo commented on templates/traceaware/deployment.yaml
> +            - 'until psql -c "SELECT 1" "user=postgres password={{ .Values.jetdb.auth.postgresPassword }} dbname=trace_aware_prod host={{ .Values.jetdb.fullnameOverride }}"; do echo waiting for trace
当时设计的时候是用同一个的 这样 project_man 能直接从数据库里面读日志 否则只能通过 trace_aware 的接口来取

2023-10-24 02:15 UTC, fahchen commented on Chart.yaml
> +    alias: dynamicdb
确定的话就要一起调相关的命名

2023-10-24 02:17 UTC, fahchen commented on templates/traceaware/deployment.yaml
> +            - 'until psql -c "SELECT 1" "user=postgres password={{ .Values.jetdb.auth.postgresPassword }} dbname=trace_aware_prod host={{ .Values.jetdb.fullnameOverride }}"; do echo waiting for trace
现在这样会导致数据库连接池加倍的哦，得分开做成两个数据库连接

2023-10-24 02:28 UTC, vanppo commented on Chart.yaml
> +    alias: dynamicdb
就是 `ProjectMan.Repo.Dynamic` 改成 `ProjectMan.Repo.Project` 嘛 我觉得都可以 看你要不要改 dynamic 这个命名是从 Ecto 那边来的

2023-10-24 09:14 UTC, YkeLit commented on Chart.yaml
> +    alias: dynamicdb
要改的话 env 也要改吧

2023-10-24 09:22 UTC, YkeLit commented on README.md
> +| jetdb.auth.postgresPassword | string | `"changeit"` | postgres 用户密码设置 |
secret 资源来存这些密码哇，单独设置 secrets 一级

2023-10-24 09:23 UTC, YkeLit commented on README.md
> +| jetTLS | object | `{}` | tls 证书 |
这个是 secret 资源的嘛

2023-10-24 09:23 UTC, YkeLit commented on templates/_helpers.tpl
> +{{- define "jet-helm-chart.imagePullSecret" }}
这个也是 secret

2023-10-25 01:44 UTC, fahchen commented on README.md
> +| jetdb.auth.postgresPassword | string | `"changeit"` | postgres 用户密码设置 |
对

2023-10-25 01:46 UTC, fahchen commented on README.md
> +| jetTLS | object | `{}` | tls 证书 |
现在在 values里面存放的是证书，要改成 secret 的名字，secret 单独创建，不在这个 chart 中维护

2023-10-25 05:03 UTC, YkeLit commented on templates/_helpers.tpl
> +{{- define "jet-helm-chart.selectorLabels" -}}
https://helm.sh/zh/docs/chart_best_practices/templates/#%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E7%9A%84%E5%90%8D%E7%A7%B0
官方并没有明确规范模版名称，但是有个建议，这个是通过 `helm create` 创建出来的模版之一。命名的话更推荐小驼峰吧。

2023-10-25 06:11 UTC, YkeLit commented on templates/breeze/_helpers.tpl
> +{{- if .Chart.AppVersion }}
https://helm.sh/zh/docs/topics/charts/#chartyaml-%E6%96%87%E4%BB%B6
这个字段是可选字段，所以加了个判断避免报错

2023-10-25 07:23 UTC, YkeLit commented on templates/breeze/ingressroute.yaml
> +{{- $webMiddlewares = append $webMiddlewares "redirect-to-https" }}
traefik 有个 `--entrypoints.<name>.http.redirections.entrypoint.to=websecure` 可以设置
https://doc.traefik.io/traefik/reference/static-configuration/cli/

2023-10-25 08:56 UTC, fahchen commented on templates/_helpers.tpl
> +{{- define "jet-helm-chart.selectorLabels" -}}
就统一成小驼峰吧

2023-10-25 08:56 UTC, fahchen commented on templates/_helpers.tpl
> +{{- define "jet-helm-chart.selectorLabels" -}}
看下能不能加个 lint 检测下

2023-10-25 08:57 UTC, fahchen commented on templates/breeze/_helpers.tpl
> +{{- if .Chart.AppVersion }}
对于我们这个具体的 chart 也是吗

2023-10-26 07:56 UTC, YkeLit commented on templates/_helpers.tpl
> +{{- define "jet-helm-chart.selectorLabels" -}}
只有手写一个，没有找到现成的 lint 工具

2023-10-26 07:57 UTC, YkeLit commented on templates/breeze/_helpers.tpl
> +{{- if .Chart.AppVersion }}
这个具体的 chart 是什么意思呀

2023-10-26 09:01 UTC, YkeLit commented on templates/_helpers.tpl
> +{{- define "jet-helm-chart.imagePullSecret" }}
这个我觉得可以留着，这个应该被 helm 统一管理起来，可以加一个调用已存在 secret 的参数。

2023-10-26 23:55 UTC, fahchen commented on templates/breeze/_helpers.tpl
> +{{- if .Chart.AppVersion }}
就是对于 jet-helm-chart 这个字段是不是可选的

2023-10-30 09:24 UTC, YkeLit commented on .github/workflows/lint-test.yaml
缺少单元测试

2023-11-17 02:48 UTC, fahchen commented on README.md
> +| resources | object | `{}` |  |
这两个应该要每个 deployment 单独控制

2023-11-17 02:48 UTC, fahchen commented on README.md
> +| jetTLS | object | `{}` | tls 证书 |
jet 的前缀要么都保留要么都不要哈

2023-11-17 02:48 UTC, fahchen commented on README.md
> +> 镜像拉取凭证使用已有凭证与新建凭证设置一个即可
1. username, password 我们应该不用了吧
2. 这里做一个教程如何做一个 image credential 的 secret，或者贴一个教程的链接

2023-11-17 02:48 UTC, fahchen commented on values.yaml
> +jetTLS: {}
jet 的前缀是否需要，保持一致哈

2023-11-17 02:48 UTC, fahchen commented on values.yaml
> +    DYNAMIC_REPO_HOSTNAME: "{{ .Values.dynamicdb.fullnameOverride }}"
这几个用 template 取值的是不是直接写到 configmap 中，不允许通过 values 文件覆盖？

2023-11-17 02:48 UTC, fahchen commented on values.yaml
> +existImageSecret: ""
```suggestion
image:
  registry: registry.cn-hangzhou.aliyuncs.com
  existingCredentialSecret: ""
```

2023-11-17 02:48 UTC, fahchen commented on templates/secrets/environment.yaml
> +  project_man_database_url: {{ .Values.secret.project_man_database_url | b64enc }}
这个地方从 values 中取出来的值，是不是还是在 values 中明文维护的呀？

2023-11-17 02:48 UTC, fahchen commented on templates/configmap/jet.yaml
我觉得这个文件可以不存在，应该没有太多变量是共用的，如果共用可以在 env 那里设置

2023-11-17 02:48 UTC, fahchen commented on templates/configmap/jet.yaml
> +  {{- tpl (.Values.env | toYaml | nindent 2) . }}
`.Values.env` 这个变量不存在哦

2023-11-17 02:48 UTC, fahchen commented on values.yaml
> +    # accessControlMaxAge: "100"
给它们分个组呢

2023-11-17 02:48 UTC, fahchen commented on templates/breeze/deployment.yaml
> +                  key: project_man_database_url
这些的组装放对应的 env 那个 configmap 里面呢

2023-11-17 02:48 UTC, fahchen commented on templates/project-man/ingressroute.yaml
> +{{- $websecureMiddlewares = append $websecureMiddlewares "compress" }}
这些是不是可以做一个 helper 来共享

2023-11-17 02:48 UTC, fahchen commented on templates/trace-aware/deployment.yaml
> +        {{- end }}
我看我们都写了 initContainer 来去检测对应的 service 有没有启动起来，如果不检测会出现什么问题呢？

2023-11-17 02:48 UTC, fahchen commented on templates/_config-map.tpl
这个文件名字改一下 config-map -> configmap

2023-11-17 02:48 UTC, fahchen commented on templates/configmap/breeze.yaml
要不你把 configmap 也维护到对应的文件夹下面吧

2023-11-17 02:52 UTC, YkeLit commented on values.yaml
> +    DYNAMIC_REPO_HOSTNAME: "{{ .Values.dynamicdb.fullnameOverride }}"
这几个也是可以覆盖的

2023-11-17 02:53 UTC, YkeLit commented on values.yaml
> +    DYNAMIC_REPO_HOSTNAME: "{{ .Values.dynamicdb.fullnameOverride }}"
这样写主要是可以将 service 中 port 的值与此处关联上

2023-11-17 02:55 UTC, YkeLit commented on templates/secrets/environment.yaml
> +  project_man_database_url: {{ .Values.secret.project_man_database_url | b64enc }}
是的，这个地方手动去添加还没想好怎么弄

2023-11-17 02:56 UTC, YkeLit commented on templates/configmap/jet.yaml
> +  {{- tpl (.Values.env | toYaml | nindent 2) . }}
存在的，在应用下面

2023-11-17 02:56 UTC, YkeLit commented on values.yaml
> +    # accessControlMaxAge: "100"
之前说把 subpath 提到顶层的哇

2023-11-20 14:25 UTC, fahchen reviewed
大体上没有问题了

2023-11-20 14:25 UTC, fahchen commented on templates/breeze/configmap.yaml
> +  DYNAMIC_REPO_EXPOSED_PORT: "5432"
这两个应该是从 dynamic db 那里来的引用值

2023-11-20 14:25 UTC, fahchen commented on templates/breeze/configmap.yaml
> +  DYNAMIC_REPO_DATABASE: dynamic_prod
这个也应该是引用值，你都检查一遍这个问题

2023-11-20 14:25 UTC, fahchen commented on values.yaml
> +    port: 50051
这个是不是没有设置的必要了？

2023-11-20 14:25 UTC, fahchen commented on values.yaml
> +      - project_man_database_url
这两个我们算不出来哇？

2023-11-20 15:16 UTC, YkeLit commented on templates/breeze/configmap.yaml
> +  DYNAMIC_REPO_DATABASE: dynamic_prod
这个值没有应用，这是init 脚本创建的库名，所以在这个文件中写死了

2023-11-20 15:25 UTC, YkeLit commented on values.yaml
> +    port: 50051
有啊，这个被 project man 的 configmap 引用

2023-11-20 15:26 UTC, YkeLit commented on values.yaml
> +      - project_man_database_url
目前算不出来

2023-11-20 15:27 UTC, YkeLit commented on templates/breeze/configmap.yaml
> +  DYNAMIC_REPO_EXPOSED_PORT: "5432"
这两个需要做成动态的吗，username 没有引用值， port 可以引用

2023-11-21 01:42 UTC, fahchen commented on values.yaml
> +    port: 50051
写到 values中就可以被覆盖哦，这个有没必要被覆盖呢？

2023-11-21 01:43 UTC, fahchen commented on templates/breeze/configmap.yaml
> +  DYNAMIC_REPO_DATABASE: dynamic_prod
如果 init 中改了，这里怎么同步呢？
或者如果用外部的数据库，这里又怎么同步呢？
思考把这些地方的变量做成一个来维护呢

2023-11-21 01:44 UTC, fahchen commented on templates/breeze/configmap.yaml
> +  DYNAMIC_REPO_EXPOSED_PORT: "5432"
它们应该和数据库的设置保持一致

2023-11-21 01:47 UTC, fahchen commented on README.md
> +| global.existingSecret.keys[4] | string | `"project_man_database_url"` |  |
这几个 key 有什么用呀？

2023-11-21 01:47 UTC, fahchen commented on README.md
> +| secret.trace_aware_database_url | string | `"ecto://postgres:changeit@jet-postgresql/trace_aware_prod"` | Trace Aware 数据库连接地址（格式：`ecto://USER:PASS@HOST/DATABASE`，[参考](https://hexdocs.pm/ecto/3.9.4/
这几个在 values 中没看到呢？

2023-11-21 02:24 UTC, YkeLit commented on templates/breeze/configmap.yaml
> +  DYNAMIC_REPO_DATABASE: dynamic_prod
这个地方的话，我之前思考过，init 暂时没有办法和这里引用。目前我能想到的是把这个提到 values 文件这一层

2023-11-21 02:28 UTC, YkeLit commented on README.md
> +| global.existingSecret.keys[4] | string | `"project_man_database_url"` |  |
这几个 key 是手动创建 secret 的 key

2023-11-22 03:12 UTC, fahchen commented on templates/breeze/deployment.yaml
> +            {{- include "jet-helm-chart.secretKeys" . | nindent 12 }}
这里不是所有的 secret 里面的 key 都被 breeze 需要的吧？

2023-11-22 03:12 UTC, fahchen commented on templates/_deployment.tpl
> +      name: jet-env-secret
这个 name 应该不是固定的吧

2023-11-22 03:14 UTC, YkeLit commented on templates/breeze/deployment.yaml
> +            {{- include "jet-helm-chart.secretKeys" . | nindent 12 }}
那就需要给他拆开了

2023-11-22 03:16 UTC, YkeLit commented on templates/_deployment.tpl
> +      name: jet-env-secret
name 直接给他固定下来比较好吧，从 README 到 资源文件都是这个名字就可以了

2023-11-22 03:24 UTC, fahchen commented on templates/breeze/deployment.yaml
> +            {{- include "jet-helm-chart.secretKeys" . | nindent 12 }}
拆开是什么意思啊？

2023-11-22 03:25 UTC, fahchen commented on templates/_deployment.tpl
> +      name: jet-env-secret
没必要固定吧，这个名字应该是安装这个 chart 的人提供的

2023-11-22 06:56 UTC, fahchen commented on values.yaml
> +  name: jet-env-secret
这个为什么放一个 namespace 呢？现在这个 existingSecret 有点不清楚是什么的
可以就叫 existingJetSecret 哇

2023-11-22 06:56 UTC, fahchen commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.secretKeys" . | nindent 12 }}
我觉得不需要这个 helper 了，直接在这里写就可以了，因为只有这里用到了

2023-11-22 09:22 UTC, YkeLit commented on values.yaml
> +  name: jet-env-secret
放一个 name 的话，方便后面加其他参数，而不会影响到这个

2023-11-22 09:27 UTC, YkeLit commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.secretKeys" . | nindent 12 }}
我给他移到 project man 目录下了

2023-11-22 09:36 UTC, fahchen commented on values.yaml
> +  name: jet-env-secret
其他的 secret 我看也没加这个东西，你举个可以例子呢

2023-11-22 13:29 UTC, YkeLit commented on values.yaml
> +  name: jet-env-secret
比如我们现在只有 project man 用了 existing， 如果后面加应用，并且需要创建新的 secret 时，就可以在 exsitingJet Secret 下添加。或者我们后面还要添加一些 secret key 可以加 key 相关的变量

2023-11-22 13:31 UTC, YkeLit commented on templates/breeze/configmap.yaml
@fahchen 这个要不要保留，因为现在没有使用

2023-11-22 13:31 UTC, YkeLit commented on templates/breeze/deployment.yaml
> +                name: {{ include "jet-helm-chart.fullname" . }}-breeze-env
这里也是

2023-11-22 13:41 UTC, YkeLit commented on values.yaml
> +    repository: jet/project_man
这里的镜像名要不要改成 jet，现在是 jet

2023-11-23 06:30 UTC, fahchen commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
project-man 这里应该也不是要所有的 secret keys 哦

2023-11-23 06:30 UTC, fahchen commented on .github/workflows/lint-test.yaml
> +        run: ct install --config .github/linters/ct.yaml
用 ct install 测试它会真实地拉取镜像和连接数据库吗？它是怎么判断测试通过的呢？

2023-11-23 06:41 UTC, YkeLit commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
这里只有 project man 在用这个 helper，所以是所有的

2023-11-23 07:56 UTC, YkeLit commented on .github/workflows/lint-test.yaml
> +        run: ct install --config .github/linters/ct.yaml
是会去拉取镜像和链接数据库的，https://github.com/helm/chart-testing/blob/1f5cd2003aed452dd324bd14b4a790b38b07b346/pkg/chart/chart.go#L517-L541
代码注释给了说明

2023-11-23 08:25 UTC, fahchen commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
projectMan 不会用全部的 key 吧

2023-11-23 08:44 UTC, YkeLit commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
![image](https://github.com/Byzanteam/jet-helm-chart/assets/48484963/8262fe48-e9a0-4eba-876d-9544136695e0)
这个 help 现在就只有这 5 个，全都是 project man 用的

2023-11-23 09:00 UTC, fahchen commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
trace-aware-database-url 呢？

2023-11-23 09:01 UTC, fahchen commented
不用一直拉我的 review
1. 你正常回复我可以收到提醒
2. 如果本次只有代码提交，改动到位了，就拉我的 review

2023-11-23 09:12 UTC, YkeLit commented
> 不用一直拉我的 review
> 
> 1. 你正常回复我可以收到提醒
> 2. 如果本次只有代码提交，改动到位了，就拉我的 review

好

2023-11-23 09:13 UTC, YkeLit commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
因为只有一个，我直接写到 deployment 的 env 里了

2023-11-23 09:15 UTC, fahchen commented on templates/trace-aware/deployment.yaml
> +                  key: project-man-password
如果使用外部的数据库，这里的东西还有问题

2023-11-23 09:16 UTC, fahchen commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
> project-man 这里应该也不是要所有的 secret keys 哦


> projectMan 不会用全部的 key 吧

所以 secret 中的东西不是全部给 projectMan 用的，所以你这里全部注入到 projectMan 中就不对了，projectMan 应该要选择自己要的

2023-11-23 09:24 UTC, YkeLit commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
![image](https://github.com/Byzanteam/jet-helm-chart/assets/48484963/ddc4a113-9e7e-4dff-b9de-78e485289364)
这里 project man 没有去加载 trace-aware-database-url  的 key 呀

2023-11-23 09:25 UTC, YkeLit commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
是要吧 jet-env-secret 这个文件拆成两个吗，分别给 trace aware 和 project man

2023-11-23 09:25 UTC, fahchen commented on templates/project-man/deployment.yaml
> +            {{- include "jet-helm-chart.projectManSecretKeys" . | nindent 12 }}
我没注意到这里😅

2023-11-23 09:27 UTC, YkeLit commented on templates/trace-aware/deployment.yaml
> +                  key: project-man-password
如果使用外部数据库，这里不会创建 initcontainer

2023-11-24 01:25 UTC, fahchen approved these changes
🧡💙💚💛💜❤️

2023-11-24 03:03 UTC, merged